[package]
name = "psico_server"
version = "0.1.0"
authors = ["Victor Lopez <A01336434@itesm.mx>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
actix-files = "0.4"